src/Web/Pages/Admin/ApplicationDetail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Web.Areas.Identity.Data;
using Web.Domain.Entities;
using Web.Infrastructure.Data;

namespace Web.Pages.Admin
{
    public class ApplicationDetailModel : PageModel
    {
        private readonly ApplicationDbContext context;
        private readonly UserManager<ApplicationUser> userManager;

        [BindProperty]
        public InputModel Input { get; set; }

        public class InputModel
        {
            public Guid RequestId { get; set; }
            public SupportStatus Status { get; set; }
            public string StatusReason { get; set; }
            public string Title { get; set; }
            public string Address { get; set; }
            public string Description { get; set; }
            public RequestType RequestType { get; set; }


            public string FirstName { get; set; }
            public string LastName { get; set; }
            public string IdentityCardNumber { get; set; }
            public int Age { get; set; }
            public Gender Gender { get; set; }
            public double MonthlyIncome { get; set; }
            public string Phone { get; set; }
            public string Email { get; set; }
        }

        public ApplicationDetailModel(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            this.context = context;
            this.userManager = userManager;
            this.Input = new InputModel();
        }

        public async Task OnGet(Guid id)
        {
            var supportDetail = await context.SupportDetails.FirstOrDefaultAsync(s => s.Id.Equals(id));
            var user = await userManager.FindByIdAsync(supportDetail.UserId.ToString());
            
            Input.FirstName = user.FirstName;
            Input.LastName = user.LastName;
            Input.Email = user.Email;
            Input.IdentityCardNumber = user.IdentityCardNumber;
            Input.Age = user.Age;
            Input.Gender = user.Gender;
            Input.Phone = user.PhoneNumber;
            Input.MonthlyIncome = user.MonthlyIncome;

            Input.RequestId = id;
            Input.Title = supportDetail.Title;
            Input.RequestType = supportDetail.RequestType;
            Input.Status = supportDetail.Status;
            Input.StatusReason = supportDetail.StatusReason;
            Input.Address = supportDetail.Address;
            Input.Description = supportDetail.Description;
        }

        public async Task<IActionResult> OnPost(Guid id)
        {
            var supportDetailEntity = await context.SupportDetails.FirstOrDefaultAsync(s => s.Id.Equals(id));
            supportDetailEntity.Status = Input.Status;
            supportDetailEntity.StatusReason = Input.StatusReason;
            context.SupportDetails.Update(supportDetailEntity);
            await context.SaveChangesAsync();
            return Redirect("/admin");
        }
    }
}

src/Web/Pages/Admin/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Web.Areas.Identity.Data;
using Web.Domain.Entities;
using Web.Infrastructure.Data;

namespace Web.Pages.Admin
{
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext context;
        private readonly UserManager<ApplicationUser> userManager;

        public List<SupportDetail> SupportDetails { get; set; }

        public IndexModel(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            this.context = context;
            this.userManager = userManager;
            SupportDetails = context.SupportDetails.OrderByDescending(s => s.Title).ToList();
        }

        public void OnGet()
        {

        }

        public void onPost()
        {

        }

        public async Task OnPostApprove(Guid id)
        {
            var supportDetailEntity = await context.SupportDetails.SingleOrDefaultAsync(s => s.Id.Equals(id));
            supportDetailEntity.Status = SupportStatus.Approved;
            await context.SaveChangesAsync();
        }

        public async Task OnPostReject(Guid id)
        {
            var supportDetailEntity = await context.SupportDetails.SingleOrDefaultAsync(s => s.Id.Equals(id));
            supportDetailEntity.Status = SupportStatus.Rejected;
            await context.SaveChangesAsync();
        }

    }
}

src/Web/Pages/Admin/ApplicationDetail.cshtml
@page "{id?}"
@model Web.Pages.Admin.ApplicationDetailModel
@{
    ViewData["Title"] = "ApplicationDetail";
}

<h1>[@Model.Input.RequestType] - @Model.Input.Title</h1>

<form class="needs-validation" asp-page="admin/ApplicationDetail/@Model.Input.RequestId" method="post">
    <div class="form-row">
        <div class="col-md-4 mb-3">
            <label asp-for="Input.FirstName">First name</label>
            <input asp-for="Input.FirstName" class="form-control" placeholder="First name" value="@Model.Input.FirstName" disabled>
        </div>
        <div class="col-md-4 mb-3">
            <label asp-for="Input.LastName">Last name</label>
            <input asp-for="Input.LastName" class="form-control" placeholder="Last name" value="@Model.Input.LastName" disabled>
        </div>
        <div class="col-md-4 mb-3">
            <label asp-for="Input.Email">Email</label>
            <input asp-for="Input.Email" class="form-control" placeholder="Email" value="@Model.Input.Email" disabled>
        </div>
    </div>

    <div class="form-row">
        <div class="col-md-4 mb-3">
            <label asp-for="Input.IdentityCardNumber">IC Number</label>
            <input asp-for="Input.IdentityCardNumber" class="form-control" placeholder="IC Number" value="@Model.Input.IdentityCardNumber" disabled>
        </div>
        <div class="col-md-4 mb-3">
            <label asp-for="Input.Gender">Gender</label>
            <input asp-for="Input.Gender" class="form-control" placeholder="Gender" value="@Model.Input.Gender" disabled>
        </div>
        <div class="col-md-4 mb-3">
            <label asp-for="Input.Age">Age</label>
            <input asp-for="Input.Age" class="form-control" placeholder="Age" value="@Model.Input.Age" disabled>
        </div>
    </div>

    <div class="form-row">
        <div class="col-md-12">
            <label asp-for="Input.Address">Address</label>
            <input asp-for="Input.Address" class="form-control" placeholder="Address" value="@Model.Input.Address" disabled>
        </div>
    </div>

    <div class="form-row">
        <div class="col-md-6 mb-3">
            <label asp-for="Input.Phone">Phone</label>
            <input asp-for="Input.Phone" class="form-control" placeholder="Phone" value="@Model.Input.Phone" disabled>
        </div>
        <div class="col-md-6 mb-3">
            <label asp-for="Input.MonthlyIncome">Monthly Income</label>
            <input asp-for="Input.MonthlyIncome" class="form-control" placeholder="Monthly Income" value="@Model.Input.MonthlyIncome" disabled>
        </div>

    </div>

    <div class="form-group">
        <label asp-for="Input.Description">Request Description</label>
        <textarea asp-for="Input.Description" class="form-control" disabled>@Model.Input.Description</textarea>
    </div>


    <div class="form-group">
        <label asp-for="Input.Status">Status</label>
        <select asp-for="Input.Status" class="custom-select" asp-items="Html.GetEnumSelectList<Web.Domain.Entities.SupportStatus>()">
        </select>
        <span asp-validation-for="Input.Status"></span>
    </div>

    <div class="form-group">
        <label asp-for="Input.StatusReason">Reason</label>
        <textarea asp-for="Input.StatusReason" class="form-control" placeholder="Reason">@Model.Input.StatusReason</textarea>
        <span asp-validation-for="Input.StatusReason"></span>
    </div>

    <button class="btn btn-primary" type="submit">Submit form</button>
    <a class="btn btn-outline-secondary" asp-page="/Admin/Index" >Go Back</a>
</form>

src/Web/Pages/Admin/Index.cshtml
@page

@model Web.Pages.Admin.IndexModel
@{
    ViewData["Title"] = "Index";
}

<h1>Support Request</h1>

<table class="table">
    <thead>
        <tr>
            <th scope="col">User Email</th>
            <th scope="col">Title</th>
            <th scope="col">Request Type</th>
            <th scope="col">Status</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.SupportDetails)
        {
        <tr>
            <td>@item.UserEmail</td>
            <td>@item.Title</td>
            <td>@item.RequestType</td>
            <td>@item.Status</td>
            <td>
                <div class="d-flex flex-row">
                    <div class="p-2">
                        <form asp-page-handler="Approve" asp-route-id="@item.Id" method="post">
                            <button type="submit" class="btn btn-success">Approve</button>
                        </form>
                    </div>

                    <div class="p-2">
                        <form asp-page-handler="Reject" asp-route-id="@item.Id" method="post">
                            <button type="submit" class="btn btn-outline-danger">Reject</button>
                        </form>
                    </div>

                    <div class="p-2">
                        <a class="btn btn-primary" asp-page="ApplicationDetail" asp-route-id="@item.Id">Detail</a>
                    </div>
                </div>



            </td>
        </tr>
        }
    </tbody>
</table>